### PR TITLE
Unified data buttons

### PR DESCRIPTION
**Pull request by Floppy**
Using alternate-rails

### CODE REVIEW

**Comment by Floppy** [comment]
This is for theodi/open-orgn-services#224

**Comment by pezholio** [comment]
The buttons look ace, but wouldn't it be better with the them on the top right? It looks OK on the main page, but they're a bit buried on the calendar pages

**Comment by pezholio** [comment]
Hmmmm... Actually, I've just tried it and it looks a bit 'button-heavy' on that right hand side now. I also know it's in keeping with the other stuff on [theodi/member-directory](https://github.com/theodi/member-directory), so happy to merge :+1:

**Comment by Floppy** [comment]
Thanks for the merge. Something about having them at the top just didn't _feel_ right, I found...

**Pull request merged**
