### PR TITLE
Fix codeclimate security issues

### PR DESCRIPTION
**Pull request by Floppy**
Session secret is not in the envs data bag. Please check it's set right when you CR this!

### CODE REVIEW

**Comment by pezholio** [comment]
Does this need to be the same as in the code? Or do we generate a new one?

**Comment by pezholio** [comment]
I suspect I know the answer, but thought I'd check first

**Comment by Floppy** [comment]
No, it's intentionally new. The one in the code should be considered compromised. (not in a bad way, as nobody cares, but you know what I mean)

**Comment by pezholio** [comment]
Aye, that's what I thought. Generated a new one and put in in the databag, so ready for merge

**Pull request merged**
